[package]

name = "scanner"
version = "0.0.1"
authors = [ "Patrick O'Doherty <p@trickod.com>" ]

[dependencies]
libc = "0.1.6"
getopts = "0.2.10"
num = "0.1.24"
enum_primitive = "0.0.2"
bitflags = "0.1.1"

[[bin]]
name = "scanner"
